gut non schema files and reorganize
GMOD/Chado pull request #100
Opened 2019-03-07 20:50 UTC by bradfordcondon

implements #79 .  The new repo will ONLY be the SQL schema and its documentation.  Perl tools for building hte diffs, for loading data, etc, will now live in the [Chado Tools repository](https://github.com/GMOD/chado_tools).

I also reorganized the repo so that everything sits at the root instead of `chado/`

2019-03-22 00:34 UTC, spficklin commented
I really like this!  Thanks for cleaning this out!  

I'm curious, though, what we do about the ``schemas`` folder.  With the new flyway approach will we continue to create a schemas folder with the fully SQL and a diff SQL?  Perhaps we should just get this PR merged in and then we can create a new issue to discuss that part.

2019-03-22 00:34 UTC, spficklin approved these changes

2019-03-22 00:36 UTC, spficklin commented
I'm going to suggest this is a medium change. I approve but I don't have the historical knowledge of Chado to know 100% sure if something was removed that shouldn't be.  So, while it looks good to me I think we need more eyes on this one.

2019-03-22 01:38 UTC, bradfordcondon commented
>I'm curious, though, what we do about the schemas folder. With the new flyway approach will we continue to create a schemas folder with the fully SQL and a diff SQL? Perhaps we should just get this PR merged in and then we can create a new issue to discuss that part.


My vision of how it would work (agreed it should be sorted in isolation from this general task of cleaning up the repo)

Diff files: **no**.  There will no longer be version-to-version diff files.

Schemas: **Yes**.  We will create full schema definitions of `1.4`, `1.5`, etc.  We will create them by simply migrating to the desired version with flyway and then dumping them.

2019-03-22 03:18 UTC, laceysanderson approved these changes
I would suggest changing the name of the `possibly_useful_old_stuff` directory to `preflyway_archive`? 😜 Otherwise this looks good to me 👍

Testing: Checked out the branch and checked the schema files I expected were still there and dug through the other remaining files (all of which I would also keep). 🤷‍♀️

2019-08-14 05:18 UTC, scottcain approved these changes
This is a beast of a pull request, though I commented a few times in the issue that I support doing it.  Since  https://github.com/GMOD/chado_tools looks good (it contains all the stuff being removed from this repo), I feel pretty good about going forward with this.

2019-08-14 20:29 UTC, scottcain commented
One other thing: I am reasonably sure looking at the "files affected" that this will not clash with the best practices pull request (https://github.com/GMOD/Chado/pull/92/files) that will place a file in chado/docs/best_practices.rst

2019-09-03 16:46 UTC, jogoodma requested changes
I would dump the `possibly_useful_old_stuff` directory altogether.

It appears to be mostly code related to and relying on the `Data::Stag` and `DBIx::DBStag` perl modules that are no longer maintained (@scottcain can you confirm this?).  Some of which is now obsolete with the native XML support in [PostgreSQL](https://www.postgresql.org/docs/current/functions-xml.html) as well. In addition, it is coupled with the Chado schema in a way that requires it to be manually maintained as the schema changes.  It will continue to degrade over time unless someone takes this on.

I see little reason to keep it around.

Other than this, everything looks great and I've verified with Pinglei that the XORT code can be dumped.  Thanks for all the work that went into this PR!

2019-09-04 15:36 UTC, jogoodma approved these changes

2019-10-15 18:26 UTC, nmenda approved these changes

2022-03-07 18:26 UTC, merged

2022-03-07 18:27 UTC, laceysanderson commented
Yay!!! 🎉